# Generated by Django 4.2.6 on 2023-11-11 01:36

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_numer',
            field=models.CharField(max_length=11, unique=True, validators=[accounts.models.validate_numbers, django.core.validators.MinLengthValidator(limit_value=11), django.core.validators.MaxLengthValidator(limit_value=11)], verbose_name='Telefone'),
        ),
    ]
