# Generated by Django 4.2.6 on 2023-11-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_phone_numer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_numer',
            new_name='phone_number',
        ),
    ]
