# Generated by Django 4.2.6 on 2024-01-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_phone_numer_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='require_otp_login',
            field=models.BooleanField(default=True),
        ),
    ]
