# Generated by Django 4.2.6 on 2024-05-13 19:28
import os
from datetime import date
from django.contrib.auth.hashers import make_password
from django.db import migrations


def create_initial_user(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    default_password = os.environ.get('DEFAULT_USER_PASSWORD')

    if not default_password:
        raise ValueError("DEFAULT_USER_PASSWORD environment variable not set!")
    print(default_password)

    default_email = os.environ.get( 'DEFAULT_USER_MAIL', 'email@admin.com')
    default_phone = os.environ.get('DEFAULT_USER_PHONE', '48999999999')

    default_user = CustomUser.objects.create(
        password=make_password(default_password),
        last_login=None,
        is_superuser=False,
        username="Administrativo",
        first_name="Usuario Padrão",
        last_name="Administrativo",
        is_staff=True,
        is_active=True,
        date_joined=date.today(),
        email= default_email,
        otp=None,
        phone_number= default_phone,
        require_otp_login=False,
    )


def assign_group(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    Group = apps.get_model('auth', 'Group')

    default_user = CustomUser.objects.get(username="Administrativo")
    administrativo_group = Group.objects.get(name='Administrativo')
    default_user.groups.add(administrativo_group)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_email'),
        ('auth', '0012_alter_user_first_name_max_length')
    ]

    operations = [
        migrations.RunPython(create_initial_user),
        migrations.RunPython(assign_group),
    ]
