# Generated by Django 4.2.6 on 2024-05-13 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_email'),
        ('accounts', '0006_zz_initial_user_data'),
    ]

    operations = [
    ]
