# Generated by Django 4.2.5 on 2023-09-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastropacientes',
            name='desligado',
            field=models.BooleanField(default=False, help_text='Paciente desligado', verbose_name='Desligado'),
        ),
    ]
