# Generated by Django 4.2.6 on 2023-11-11 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastroprofissionais',
            old_name='endereco_completmento',
            new_name='endereco_complemento',
        ),
    ]
