# Generated by Django 4.2.5 on 2023-09-11 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cadastropacientes_desligado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastropacientes',
            options={'permissions': [('transfer_pac', 'Transferir Paciente (Terapeutas)'), ('deslig_pac', 'Desligar Paciente (Terapeutas)')], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='cadastroprofissionais',
            options={'permissions': [('add_user', 'Pode adicionar novos usuarios (Administrativos)')], 'verbose_name': 'Terapeuta', 'verbose_name_plural': 'Terapeutas'},
        ),
        migrations.AlterModelOptions(
            name='prontuarios',
            options={'permissions': [('add_entry', 'Adicionar entradas em prontuários (Terapeutas)')], 'verbose_name': 'Prontuário', 'verbose_name_plural': 'Prontuários'},
        ),
    ]
