# Generated by Django 4.2.5 on 2023-09-11 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cadastropacientes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastroprofissionais',
            options={'permissions': [('add_user', 'Adicionar novos Usuários (Administrativos)')], 'verbose_name': 'Terapeuta', 'verbose_name_plural': 'Terapeutas'},
        ),
    ]
