# Generated by Django 4.2.6 on 2023-11-13 14:25

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cadastroprofissionais_endereco_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroprofissionais',
            name='endereco_numero',
            field=models.CharField(max_length=7, validators=[main.models.validate_numbers], verbose_name='Número'),
        ),
    ]
