# Generated by Django 4.2.5 on 2023-09-12 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cadastroprofissionais_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastroprofissionais',
            options={'permissions': [('add_terapeuta', 'Adicionar novos Usuários (Administrativos)')], 'verbose_name': 'Terapeuta', 'verbose_name_plural': 'Terapeutas'},
        ),
        migrations.AlterModelOptions(
            name='conveniosaceitos',
            options={'permissions': [('add_convenio', 'Adicionar Novo Convenio (Administrativos)')], 'verbose_name': 'Convênio', 'verbose_name_plural': 'Convênios'},
        ),
        migrations.RenameField(
            model_name='cadastropacientes',
            old_name='cpf',
            new_name='cpf_numero',
        ),
    ]
