# Generated by Django 4.2.6 on 2023-12-05 12:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_endereco_completmento_cadastropacientes_endereco_complemento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastropacientes',
            name='cep_numero',
            field=models.CharField(max_length=8, validators=[main.models.validate_numbers, django.core.validators.MinLengthValidator(limit_value=8)], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='cadastropacientes',
            name='cidade',
            field=models.CharField(max_length=100, validators=[main.models.validate_letters, django.core.validators.MinLengthValidator(limit_value=3)], verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='cadastroprofissionais',
            name='cep_numero',
            field=models.CharField(max_length=8, validators=[main.models.validate_numbers, django.core.validators.MinLengthValidator(limit_value=8)], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='cadastroprofissionais',
            name='cidade',
            field=models.CharField(max_length=20, validators=[main.models.validate_letters, django.core.validators.MinLengthValidator(limit_value=3)], verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='conveniosaceitos',
            name='cep_numero',
            field=models.CharField(max_length=8, validators=[main.models.validate_numbers, django.core.validators.MinLengthValidator(limit_value=8)], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='conveniosaceitos',
            name='cidade',
            field=models.CharField(max_length=20, validators=[main.models.validate_letters, django.core.validators.MinLengthValidator(limit_value=3)], verbose_name='Cidade'),
        ),
        migrations.CreateModel(
            name='HistoricoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=30, validators=[main.models.validate_letters], verbose_name='Curso')),
                ('instituicao', models.CharField(max_length=50, validators=[main.models.validate_letters], verbose_name='Instituição')),
                ('ano_conclusao', models.CharField(max_length=4, validators=[main.models.validate_numbers, django.core.validators.MinLengthValidator(limit_value=4)], verbose_name='Ano de Conclusão')),
                ('profissonal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.cadastroprofissionais', verbose_name='Terapeuta')),
            ],
            options={
                'verbose_name': 'Histórico Academico',
                'verbose_name_plural': 'Históricos Academicos',
            },
        ),
    ]
