# Generated by Django 4.2.5 on 2023-09-14 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_cadastroprofissionais_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastropacientes',
            name='modalidade_atendimento',
            field=models.IntegerField(choices=[(0, 'Individual'), (1, 'Grupo'), (2, 'Casal')], default=0, verbose_name='Modalidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadastropacientes',
            name='convenio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='main.conveniosaceitos'),
        ),
        migrations.AlterField(
            model_name='cadastropacientes',
            name='terapeuta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='main.cadastroprofissionais'),
        ),
        migrations.AlterField(
            model_name='cadastroprofissionais',
            name='usuario_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Terapeutas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prontuarios',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prontuarios', to='main.cadastroprofissionais', to_field='nome', verbose_name='Terapeuta'),
        ),
        migrations.AlterField(
            model_name='prontuarios',
            name='numero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paciente', to='main.cadastropacientes', to_field='prontuario_numero', verbose_name='Nº de Prontuário'),
        ),
        migrations.CreateModel(
            name='CadastroGrupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Nome')),
                ('prontuario_grupo_numero', models.CharField(max_length=4, verbose_name='Nº Prontuário do Grupo')),
                ('terapeuta_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='main.cadastroprofissionais')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.AddField(
            model_name='cadastropacientes',
            name='prontuario_coletivo_numero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membros', to='main.cadastrogrupos'),
        ),
    ]
