# Generated by Django 4.2.5 on 2023-09-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cadastropacientes_modalidade_atendimento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastropacientes',
            old_name='prontuario_coletivo_numero',
            new_name='grupo',
        ),
    ]
