# Generated by Django 4.2.6 on 2023-12-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_cadastropacientes_cep_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastropacientes',
            name='email',
            field=models.EmailField(default='teste@mail.com', max_length=254, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conveniosaceitos',
            name='email',
            field=models.EmailField(default='teste@mail.com', max_length=254, verbose_name='E-mail para Contato'),
            preserve_default=False,
        ),
    ]
