# Generated by Django 4.2.5 on 2023-09-18 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_prontuario_coletivo_numero_cadastropacientes_grupo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastrogrupos',
            options={'permissions': [('transfer_group', 'Transferir Grupo (Terapeutas)'), ('deslig_group', 'Desligar Grupo (Terapeutas)')], 'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterModelOptions(
            name='cadastropacientes',
            options={'permissions': [('transfer_pac', 'Transferir Paciente (Terapeutas)'), ('deslig_pac', 'Desligar Paciente (Terapeutas)'), ('add_pac_group', 'Adicionar Paciente a Grupo (Terapeutas')], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterField(
            model_name='cadastrogrupos',
            name='prontuario_grupo_numero',
            field=models.CharField(max_length=4, unique=True, verbose_name='Nº Prontuário do Grupo'),
        ),
        migrations.CreateModel(
            name='ProntuariosGrupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(auto_now_add=True, verbose_name='Data da Entrada')),
                ('data_consulta', models.DateField(verbose_name='Data da Consulta')),
                ('entrada', models.TextField(verbose_name='Parecer')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prontuario_grupo', to='main.cadastroprofissionais', to_field='nome', verbose_name='Terapeuta Responsável')),
                ('numero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupo', to='main.cadastrogrupos', to_field='prontuario_grupo_numero', verbose_name='Nº Prontuário do Grupo')),
            ],
            options={
                'verbose_name': 'Prontuário Grupo',
                'verbose_name_plural': 'Prontuários Grupos',
                'permissions': [('add_entry_group', 'Adicionar entradas em prontuários de Grupo (Terapeutas)')],
            },
        ),
    ]
