# Generated by Django 4.2.6 on 2023-12-05 13:23

import django.core.validators
from django.db import migrations, models
import main.models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_cadastropacientes_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroprofissionais',
            name='pos_grad_status',
            field=models.IntegerField(choices=[(0, 'Nível 1 - Incompleto'), (1, 'Nível 1 - Completo'), (2, 'Nível 2 - Incompleto'), (3, 'Nível 2 - Completo'), (4, 'Nível 3 - Incompleto'), (5, 'Nível 3 - Completo')], default=0, verbose_name='Status Pós'),
        ),
        migrations.AlterField(
            model_name='conveniosaceitos',
            name='responsavel_contato',
            field=models.CharField(max_length=50, validators=[main.models.validate_letters, django.core.validators.MinLengthValidator(limit_value=3)], verbose_name='Nome do Resposável'),
        ),
    ]
