# Generated by Django 4.2.5 on 2023-09-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_cadastrogrupos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrogrupos',
            name='prontuario_grupo_numero',
            field=models.CharField(max_length=5, unique=True, verbose_name='Nº Prontuário do Grupo'),
        ),
    ]
