# Generated by Django 4.2.6 on 2023-12-05 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_cadastroprofissionais_pos_grad_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicoacademico',
            options={'verbose_name': 'Histórico Acadêmico', 'verbose_name_plural': 'Históricos Acadêmicos'},
        ),
    ]
