# Generated by Django 4.2.6 on 2024-02-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_historicoacademico_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastrogrupos',
            old_name='terapeuta_auxiliar1',
            new_name='terapeuta_auxiliar',
        ),
    ]
