# Generated by Django 4.2.5 on 2023-09-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_cadastrogrupos_prontuario_grupo_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrogrupos',
            name='data_final',
            field=models.DateField(blank=True, help_text='dd/mm/aaaa', null=True, verbose_name='Data do Desligamento'),
        ),
        migrations.AddField(
            model_name='cadastrogrupos',
            name='data_inicio',
            field=models.DateField(default='2020-10-10', help_text='dd/mm/aaaa', verbose_name='Data de Inicio'),
        ),
        migrations.AddField(
            model_name='cadastrogrupos',
            name='desligado',
            field=models.BooleanField(default=False, help_text='Paciente desligado', verbose_name='Desligado'),
        ),
    ]
