# Generated by Django 4.2.5 on 2023-09-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_cadastrogrupos_data_final_cadastrogrupos_data_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrogrupos',
            name='data_inicio',
            field=models.DateField(help_text='dd/mm/aaaa', verbose_name='Data de Inicio'),
        ),
    ]
