# Generated by Django 4.2.6 on 2023-10-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_cadastrogrupos_data_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrogrupos',
            name='desligado',
            field=models.BooleanField(default=False, help_text='Grupo encerrado', verbose_name='Detativado'),
        ),
    ]
