# Generated by Django 4.2.6 on 2024-02-27 15:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_prontuarios_prontuariosindividuais'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastropacientes',
            name='cpf_responsavel_legal',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[main.models.validate_numbers, django.core.validators.MinLengthValidator(limit_value=11)], verbose_name='CPF do Responsável'),
        ),
        migrations.AlterField(
            model_name='cadastropacientes',
            name='cpf_numero',
            field=models.CharField(help_text='CPF de menores consta na Certidão de nascimento', max_length=11, unique=True, validators=[
                main.models.validate_numbers, django.core.validators.MinLengthValidator(limit_value=11)], verbose_name='CPF'),
        ),
        migrations.CreateModel(
            name='ProfissionaisMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, help_text='Arquivos PDF', null=True, upload_to=main.models.terapeutas_media_upload_path, verbose_name='PDF')),
                ('image_files', models.ImageField(blank=True, help_text='Arquivos de Imagem', null=True, upload_to=main.models.terapeutas_media_upload_path, verbose_name='Imagens')),
                ('description', models.CharField(help_text='Descreva o arquivo', max_length=255, verbose_name='Descrição')),
                ('terapeuta', models.ForeignKey(help_text='Terapeuta relacionado', on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='main.cadastroprofissionais', verbose_name='Terapeuta')),
            ],
            options={
                'verbose_name': 'Arquivo de Terapeuta',
                'verbose_name_plural': 'Arquivos de Terapeuta',
            },
        ),
        migrations.CreateModel(
            name='PacientesMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, help_text='Arquivos PDF', null=True, upload_to=main.models.pacientes_media_upload_path, verbose_name='PDF')),
                ('image_files', models.ImageField(blank=True, help_text='Arquivos de Imagem', null=True, upload_to=main.models.pacientes_media_upload_path, verbose_name='Imagens')),
                ('description', models.CharField(help_text='Descreva o arquivo', max_length=255, verbose_name='Descrição')),
                ('paciente', models.ForeignKey(help_text='Paciente relacionado', on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='main.cadastropacientes', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Arquivo de Paciente',
                'verbose_name_plural': 'Arquivos de Pacientes',
            },
        ),
    ]
