# Generated by Django 4.2.6 on 2023-10-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_cadastrogrupos_desligado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrogrupos',
            name='desligado',
            field=models.BooleanField(default=False, help_text='Grupo encerrado', verbose_name='Desativado'),
        ),
    ]
