# Generated by Django 4.2.6 on 2023-11-07 13:01

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_cadastrogrupos_desligado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrogrupos',
            name='prontuario_grupo_numero',
            field=models.CharField(max_length=5, unique=True, validators=[main.models.validate_numbers], verbose_name='Nº Prontuário do Grupo'),
        ),
        migrations.AlterField(
            model_name='cadastropacientes',
            name='carteirinha_convenio',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[main.models.validate_numbers], verbose_name='Número do Convênio'),
        ),
        migrations.AlterField(
            model_name='cadastropacientes',
            name='cpf_numero',
            field=models.CharField(max_length=11, unique=True, validators=[main.models.validate_numbers], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cadastropacientes',
            name='nome',
            field=models.CharField(max_length=100, validators=[main.models.validate_letters], verbose_name='Nome do Paciente'),
        ),
        migrations.AlterField(
            model_name='cadastropacientes',
            name='prontuario_numero',
            field=models.CharField(max_length=7, unique=True, validators=[main.models.validate_numbers], verbose_name='Nº de Prontuario'),
        ),
        migrations.AlterField(
            model_name='cadastropacientes',
            name='responsavel_legal',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[main.models.validate_letters], verbose_name='Responsável Legal'),
        ),
        migrations.AlterField(
            model_name='cadastropacientes',
            name='telefone_numero',
            field=models.CharField(max_length=11, validators=[main.models.validate_numbers], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='cadastroprofissionais',
            name='conselho_codigo',
            field=models.CharField(max_length=5, unique=True, validators=[main.models.validate_numbers], verbose_name='CRP'),
        ),
        migrations.AlterField(
            model_name='cadastroprofissionais',
            name='nome',
            field=models.CharField(max_length=100, unique=True, validators=[main.models.validate_letters], verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cadastroprofissionais',
            name='telefone_numero',
            field=models.CharField(max_length=11, validators=[main.models.validate_numbers], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='cadastroprofissionais',
            name='unimed_codigo',
            field=models.CharField(max_length=6, unique=True, validators=[main.models.validate_numbers], verbose_name='Número cadastro Unimed'),
        ),
    ]
