# Generated by Django 4.2.6 on 2023-11-10 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_cadastrogrupos_prontuario_grupo_numero_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastropacientes',
            options={'ordering': ['nome'], 'permissions': [('transfer_pac', 'Transferir Paciente (Terapeutas)'), ('deslig_pac', 'Desligar Paciente (Terapeutas)'), ('add_pac_group', 'Adicionar Paciente a Grupo (Terapeutas')], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.CreateModel(
            name='PresencasGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Consulta', to='main.prontuariosgrupos', verbose_name='Consulta')),
                ('grupo_prontuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.cadastrogrupos', to_field='prontuario_grupo_numero', verbose_name='Grupo nº')),
                ('pacientes', models.ManyToManyField(to='main.cadastropacientes')),
            ],
            options={
                'verbose_name': 'Presença',
                'verbose_name_plural': 'Presenças',
            },
        ),
    ]
