# Generated by Django 4.2.6 on 2024-03-06 12:15

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_cadastrogrupos_data_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoacademico',
            name='certificado',
            field=models.FileField(blank=True, help_text='Arquivos PDF', null=True, upload_to=main.models.terapeutas_media_upload_path, verbose_name='PDF'),
        ),
    ]
