# Generated by Django 4.2.6 on 2024-03-13 13:00

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_historicoacademico_certificado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicoacademico',
            name='certificado',
        ),
        migrations.AddField(
            model_name='historicoacademico',
            name='certificado_conclusao',
            field=models.FileField(blank=True, help_text='Apenas arquivos PDF', upload_to=main.models.terapeutas_media_upload_path, verbose_name='Certificado de Conclusão'),
        ),
        migrations.AlterField(
            model_name='historicoacademico',
            name='ano_conclusao',
            field=models.IntegerField(validators=[main.models.validate_numbers, django.core.validators.MinLengthValidator(limit_value=4), django.core.validators.MaxLengthValidator(limit_value=4)], verbose_name='Ano de Conclusão'),
        ),
        migrations.AlterField(
            model_name='historicoacademico',
            name='instituicao',
            field=models.CharField(max_length=50, validators=[main.models.validate_letters, django.core.validators.MinLengthValidator(limit_value=4)], verbose_name='Instituição'),
        ),
    ]
