# Generated by Django 4.2.6 on 2024-03-18 12:22

import datetime
import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_historicoacademico_certificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastropacientes',
            name='cpf_numero',
            field=models.CharField(help_text='CPF de menores consta na Certidão de Nascimento', max_length=11, unique=True, validators=[main.models.validate_numbers, django.core.validators.MinLengthValidator(limit_value=11)], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cadastropacientes',
            name='data_inicio',
            field=models.DateField(default=datetime.datetime.now, help_text='dd/mm/aaaa', verbose_name='Data de Inicio'),
        ),
        migrations.AlterField(
            model_name='cadastropacientes',
            name='prontuario_numero',
            field=models.CharField(default=main.models.create_prontuario_numero, max_length=7, unique=True, validators=[main.models.validate_numbers, django.core.validators.MinLengthValidator(limit_value=7)], verbose_name='Nº de Prontuario'),
        ),
        migrations.AlterField(
            model_name='conveniosaceitos',
            name='cep_numero',
            field=models.CharField(max_length=8, null=True, validators=[main.models.validate_numbers, django.core.validators.MinLengthValidator(limit_value=8)], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='conveniosaceitos',
            name='cidade',
            field=models.CharField(max_length=20, null=True, validators=[main.models.validate_letters, django.core.validators.MinLengthValidator(limit_value=3)], verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='conveniosaceitos',
            name='cnpj_numero',
            field=models.CharField(max_length=14, null=True, validators=[main.models.validate_numbers, django.core.validators.MinLengthValidator(limit_value=14)], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='conveniosaceitos',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='E-mail para Contato'),
        ),
        migrations.AlterField(
            model_name='conveniosaceitos',
            name='endereco_bairro',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=3)], verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='conveniosaceitos',
            name='endereco_complemento',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=4)], verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='conveniosaceitos',
            name='endereco_numero',
            field=models.CharField(max_length=7, null=True, validators=[main.models.validate_numbers], verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='conveniosaceitos',
            name='endereco_rua',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=10)], verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='conveniosaceitos',
            name='responsavel_contato',
            field=models.CharField(max_length=50, null=True, validators=[main.models.validate_letters, django.core.validators.MinLengthValidator(limit_value=3)], verbose_name='Nome do Resposável'),
        ),
        migrations.AlterField(
            model_name='conveniosaceitos',
            name='telefone_numero',
            field=models.CharField(max_length=11, null=True, validators=[main.models.validate_numbers, django.core.validators.MinLengthValidator(limit_value=11)], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='historicoacademico',
            name='ano_conclusao',
            field=models.CharField(max_length=4, validators=[main.models.validate_numbers, django.core.validators.MinLengthValidator(limit_value=4)], verbose_name='Ano de Conclusão'),
        ),
    ]
