# Generated by Django 4.2.6 on 2024-03-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_cadastropacientes_cpf_numero_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicoacademico',
            old_name='profissonal',
            new_name='terapeuta',
        ),
    ]
