# Generated by Django 4.2.6 on 2024-03-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_profissonal_historicoacademico_terapeuta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientesmedia',
            old_name='image_files',
            new_name='image_file',
        ),
        migrations.RenameField(
            model_name='profissionaismedia',
            old_name='image_files',
            new_name='image_file',
        ),
    ]
