# Generated by Django 4.2.6 on 2024-03-20 14:29

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_pacientesmedia_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissionaismedia',
            name='image_file',
            field=models.ImageField(blank=True, default='n/d', help_text='Arquivos de Imagem', null=True, upload_to=main.models.terapeutas_media_upload_path, verbose_name='Imagens'),
        ),
        migrations.AlterField(
            model_name='profissionaismedia',
            name='pdf_file',
            field=models.FileField(blank=True, default='n/d', help_text='Arquivos PDF', null=True, upload_to=main.models.terapeutas_media_upload_path, verbose_name='PDF'),
        ),
    ]
