# Generated by Django 4.2.6 on 2024-03-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_profissionaismedia_image_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastrogrupos',
            options={'permissions': [('transfer_group', 'Transferir Grupo (Terapeutas)'), ('deslig_group', 'Desligar Grupo (Terapeutas)'), ('create_group', 'Cadastrar Grupo (Terapeutas)')], 'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterModelOptions(
            name='cadastropacientes',
            options={'ordering': ['nome'], 'permissions': [('transfer_pac', 'Transferir Paciente (Terapeutas)'), ('deslig_pac', 'Desligar Paciente (Terapeutas)'), ('add_pac_group', 'Adicionar Paciente a Grupo (Terapeutas)'), ('remove_pac_from_group', 'Remover Paciente de um Grupo (Terapeutas)')], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
    ]
