# Generated by Django 4.2.6 on 2024-04-10 14:34

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_cadastrogrupos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrogrupos',
            name='terapeuta_auxiliar',
            field=models.ManyToManyField(blank=True, to='main.cadastroprofissionais', verbose_name='Ego Auxiliar'),
        ),
        migrations.AlterField(
            model_name='cadastropacientes',
            name='modalidade_atendimento',
            field=models.IntegerField(choices=[(0, 'Individual'), (1, 'Grupo'), (2, 'Casal')], default=0, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='historicoacademico',
            name='ano_conclusao',
            field=models.CharField(default=2024, max_length=4, validators=[main.models.validate_numbers, django.core.validators.MinLengthValidator(limit_value=4), django.core.validators.MinValueValidator(limit_value=1900), django.core.validators.MaxValueValidator(limit_value=2024)], verbose_name='Ano de Conclusão'),
        ),
    ]
